package com.boredream.herb.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.boredream.herb.db.Herb;
import com.boredream.herb.db.HerbDetail;

import com.boredream.herb.db.HerbDao;
import com.boredream.herb.db.HerbDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig herbDaoConfig;
    private final DaoConfig herbDetailDaoConfig;

    private final HerbDao herbDao;
    private final HerbDetailDao herbDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        herbDaoConfig = daoConfigMap.get(HerbDao.class).clone();
        herbDaoConfig.initIdentityScope(type);

        herbDetailDaoConfig = daoConfigMap.get(HerbDetailDao.class).clone();
        herbDetailDaoConfig.initIdentityScope(type);

        herbDao = new HerbDao(herbDaoConfig, this);
        herbDetailDao = new HerbDetailDao(herbDetailDaoConfig, this);

        registerDao(Herb.class, herbDao);
        registerDao(HerbDetail.class, herbDetailDao);
    }
    
    public void clear() {
        herbDaoConfig.getIdentityScope().clear();
        herbDetailDaoConfig.getIdentityScope().clear();
    }

    public HerbDao getHerbDao() {
        return herbDao;
    }

    public HerbDetailDao getHerbDetailDao() {
        return herbDetailDao;
    }

}
